[package]
name = "mpi_rsmcmc"
version = "0.1.0"
authors = ["Gu Junhua <jhgu@nao.cas.cn>"]

[dependencies]
mpi = "0.5.4"
num-traits = ">0.2.*"
rand = ">=0.5.*"
mpi-sys = ">=0.1"
quickersort = ">=3.0.*"

[dependencies.scorus]
path="../scorus"
